/* Offline IIIF viewer replacement - generated by site2static (opencode:arc/apex).
   Replaces the live OpenSeadragon+info.json deep-zoom with a single high-res
   derivative served locally, reusing the on-page SVG icon symbols and the
   site's existing iiif-viewer CSS. */
document.addEventListener("DOMContentLoaded", function () {
  if (typeof OpenSeadragon === "undefined") { return; }
  var nodes = document.querySelectorAll("[data-iiif-offline]");
  var svgns = "http://www.w3.org/2000/svg";
  var xlinkns = "http://www.w3.org/1999/xlink";
  function makeButton(id, iconId, label) {
    var b = document.createElement("button");
    b.type = "button"; b.id = id; b.className = "iiif-viewer__button";
    b.setAttribute("aria-label", label); b.setAttribute("title", label);
    var svg = document.createElementNS(svgns, "svg");
    svg.setAttribute("viewBox", "0 0 24 24");
    svg.setAttribute("width", "24"); svg.setAttribute("height", "24");
    svg.setAttribute("fill", "currentColor"); svg.setAttribute("aria-hidden", "true");
    var use = document.createElementNS(svgns, "use");
    use.setAttributeNS(xlinkns, "href", "#" + iconId);
    svg.appendChild(use); b.appendChild(svg);
    return b;
  }
  for (var i = 0; i < nodes.length; i++) {
    (function () {
      var el = nodes[i];
      var id = el.getAttribute("data-iiif-id");
      var src = el.getAttribute("data-iiif-src");
      var mount = document.getElementById("osd-viewer-" + id);
      if (!mount || !src) { return; }
      var controls = document.createElement("div");
      controls.id = "osd-controls-" + id;
      controls.className = "iiif-viewer__controls";
      controls.appendChild(makeButton("osd-btn-zoom-in-" + id, "icon-zoom-in-" + id, "Zoom in"));
      controls.appendChild(makeButton("osd-btn-zoom-out-" + id, "icon-zoom-out-" + id, "Zoom out"));
      controls.appendChild(makeButton("osd-btn-full-page-" + id, "icon-fullscreen-" + id, "Toggle fullscreen"));
      mount.appendChild(controls);
      OpenSeadragon({
        id: "osd-viewer-" + id,
        tileSources: { type: "image", url: src },
        sequenceMode: false, showSequenceControl: false,
        showHomeControl: false, showNavigationControl: false,
        zoomInButton: "osd-btn-zoom-in-" + id,
        zoomOutButton: "osd-btn-zoom-out-" + id,
        fullPageButton: "osd-btn-full-page-" + id
      }).addHandler("open", function (e) {
        var icons = document.getElementById("osd-viewer-icons-" + id);
        if (icons) { e.eventSource.element.appendChild(icons.cloneNode(true)); }
      });
    })();
  }
});
